[package]
name = "tree-sitter-graph"
version = "0.2.0"
description = "Construct graphs from parsed source code"
homepage = "https://github.com/tree-sitter/tree-sitter-graph/"
repository = "https://github.com/tree-sitter/tree-sitter-graph/"
readme = "README.md"
license = "MIT OR Apache-2.0"
authors = [
  "Douglas Creager <dcreager@dcreager.net>"
]
edition = "2018"

[lib]
# All of our tests are in the tests/it "integration" test executable.
test = false

[dependencies]
anyhow = "1.0"
regex = "1"
smallvec = { version="1.6", features=["union"] }
thiserror = "1.0"
tree-sitter = "0.20"
serde = "1.0.117"
serde_json = "1.0.72"

[dependencies.string-interner]
version = "0.12"
default-features = false
features = ["std", "inline-more", "backends"]

[dev-dependencies]
indoc = "1.0"
tree-sitter-python = "0.19.1"

# cli-only dependencies below

[[bin]]
name = "tree-sitter-graph"
required-features = ["cli"]

[features]
cli = ["clap", "tree-sitter-config", "tree-sitter-loader"]

[dependencies.clap]
optional = true
version = "2.32"

[dependencies.tree-sitter-config]
optional = true
version = "0.19"

[dependencies.tree-sitter-loader]
optional = true
version = "0.19"
